theme: jekyll-theme-time-machine
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
title: AWS Certified DevOps Engineer - Professional (DOP-C01) Exam Notes
description: AWS Certified DevOps Engineer Notes